// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8HnD6q74B2PiqWmHD1C5mVbpNdJYI758',
    appId: '1:835014884734:web:58114c6396e25e7574472f',
    messagingSenderId: '835014884734',
    projectId: 'cins467-s23-41489',
    authDomain: 'cins467-s23-41489.firebaseapp.com',
    storageBucket: 'cins467-s23-41489.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmp1013CMMnGcsP8uYWLDWmxnGNbMTQvU',
    appId: '1:835014884734:android:190de393f368428a74472f',
    messagingSenderId: '835014884734',
    projectId: 'cins467-s23-41489',
    storageBucket: 'cins467-s23-41489.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7G9TY9_X8DnLBFvarrV8EzZhyaD2TWUQ',
    appId: '1:835014884734:ios:b27e79885c5cb51874472f',
    messagingSenderId: '835014884734',
    projectId: 'cins467-s23-41489',
    storageBucket: 'cins467-s23-41489.appspot.com',
    iosClientId: '835014884734-ncc0jm12a7kegik3mg9n78b1cp9vrs43.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7G9TY9_X8DnLBFvarrV8EzZhyaD2TWUQ',
    appId: '1:835014884734:ios:b27e79885c5cb51874472f',
    messagingSenderId: '835014884734',
    projectId: 'cins467-s23-41489',
    storageBucket: 'cins467-s23-41489.appspot.com',
    iosClientId: '835014884734-ncc0jm12a7kegik3mg9n78b1cp9vrs43.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
